"""add threat intel lookups

Revision ID: 82d6de8b3a69
Revises: ab94b124f4e4
Create Date: 2026-09-22 11:11:12.822916
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "82d6de8b3a69"
down_revision: str | None = "ab94b124f4e4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "threat_intel_lookups",
        sa.Column("url_id", sa.UUID(), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("threat_type", sa.String(length=64), nullable=True),
        sa.Column(
            "tags",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column("reference_url", sa.String(length=512), nullable=True),
        sa.Column("error", sa.String(length=256), nullable=True),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["url_id"], ["urls.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("url_id", "provider", name="uq_threat_intel_url_provider"),
    )
    op.create_index(
        op.f("ix_threat_intel_lookups_url_id"), "threat_intel_lookups", ["url_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_threat_intel_lookups_url_id"), table_name="threat_intel_lookups")
    op.drop_table("threat_intel_lookups")
    # ### end Alembic commands ###
